using System;
using System.Collections.Generic;

namespace Hotel_System.API.Models;

public partial class TienNghi
{
    // Id can be generated by server (TNxx) when creating a new amenity, so make it nullable for model binding
    public string? IdtienNghi { get; set; }

    public string TenTienNghi { get; set; } = null!;

    public virtual ICollection<TienNghiPhong> TienNghiPhongs { get; set; } = new List<TienNghiPhong>();
}
