export { default as AdultsDropdown } from "./AdultsDropdown";
export { default as PageNotFound } from "./PageNotFound";
export { default as KidsDropdown } from "./KidsDropdown";
export { default as HeroSlider } from "./HeroSlider";
export { default as BookForm } from "./BookForm";
export { default as CheckOut } from "./CheckOut";
export { default as CheckIn } from "./CheckIn";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Rooms } from "./Rooms";
export { default as RoomTypes } from "./RoomTypes";
export { default as About } from "./About";
export { default as Services } from "./Services";
export { default as Gallery } from "./Gallery";
export { default as Testimonials } from "./Testimonials";
export { default as FAQs } from "./FAQs";
export { default as CTA } from "./CTA";

export { default as ScrollToTop } from "../utils/ScrollToTop";
